// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFEyDARsam7UbaKENiauYp34UrL64Vdg',
    appId: '1:662669421840:android:d0593ac85d3d3a5cc5c995',
    messagingSenderId: '662669421840',
    projectId: 'my-1st-project-96cfb',
    storageBucket: 'my-1st-project-96cfb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOJV5xoOno-shwqLbKJ6gGruw52r8_TPU',
    appId: '1:662669421840:web:72bfb293d91505aec5c995',
    messagingSenderId: '662669421840',
    projectId: 'my-1st-project-96cfb',
    authDomain: 'my-1st-project-96cfb.firebaseapp.com',
    storageBucket: 'my-1st-project-96cfb.firebasestorage.app',
    measurementId: 'G-5FR02C0H23',
  );
}